### ISSUE TITLE
1.0.63 WebStorm plugin seem to skip including certain files

### ISSUE THREAD

**Issue by bruderstein** [wallabyjs/public#611]
### Files not included after upgrade to 1.0.63
After upgrading to 1.0.63 (core 1.0.235), wallaby is no longer copying a set of files from the `files` definition in the wallaby.js config. I've tried removing the project from the ~/.WebStorm2016.1/.../projects/ directory and restarting, and it still doesn't work. 

The files definition is `files: ['src/**/*.js', 'testHelpers/*.js']` - all files in `src` are copied, but nothing from `testHelpers`.  I've tried putting `testHelpers` first, tried including all subdirectories `testHelpers/**/*.js`, tried renaming to all lowercase `testhelpers/**/*.js`, but the project original and instrumented directories only contain the `src` and `test` directories. I've tried the same project on two machines, and get exactly the same result. With the second one I was careful to ensure it worked before the update to 1.0.63, immediately after the update it stopped working with `Cannot find module '../testHelpers/jsdomHelper'`.  

Moving the files under the `test` directory works, however.

The project is https://github.com/jedwatson/react-select - the `runner` is wrong in the current master `wallaby.js` file, just change to `node`.

### Wallaby.js configuration file

```javascript
var babel = require('babel');

module.exports = function (wallaby) { // eslint-disable-line no-unused-vars
	return {
		files: ['src/**/*.js', 'testHelpers/*.js'],
		tests: ['test/*-test.js' ],
		env: {
			type: 'node',
			 runner: 'node'
		},
		compilers: {
			'**/*.js': wallaby.compilers.babel({
				babel: babel
			})
		}
	};
};
```

### Code editor or IDE name and version

WebStorm v2016.1.2b

### OS name and version
Linux Debian jessie (8)

**Comment by ArtemGovorov** [comment]
There's been a change in 1.0.63 that may affect this. As a workaround, you may manually install [v1.0.62](http://update.wallabyjs.com/wallaby-intellij-v1.0.62.zip) (`Settings - Plugins - Install plugin from disk`) and use it while I'm investigating/fixing it.

**Comment by ArtemGovorov** [comment]
The issue is fixed in the v1.0.64. Please restart your IDE and the plugin update prompt will popup.

**Comment by bruderstein** [comment]
Awesome, thank you - confirmed it all works again :)
