### ISSUE TITLE
Pure-ES6 TypeScript test file breaking wallaby/webpack

### ISSUE THREAD

**Issue by carlansley** [wallabyjs/public#559]
### Issue description or question

The file below will break the combination of webpack & wallaby for me:

```javascript
// app/about/about.spec.ts
import {
  it,
  inject,
  describe,
  beforeEachProviders
} from 'angular2/testing';

// Load the implementations that should be tested
import {About} from './about';

describe('About', () => {
  beforeEachProviders(() => [
    About
  ]);

  it('should log ngOnInit', inject([ About ], (about) => {

    spyOn(console, 'log');
    expect(console.log).not.toHaveBeenCalled();

    about.ngOnInit();
    expect(console.log).toHaveBeenCalled();
  }));

});
```

I get an error like this:
```
src/app/about/about.spec.ts About should log ngOnInit [5 ms]

	Error: Cannot find module '786'
		at config/spec-bundle.js:49
		at config/spec-bundle.js:52
		at config/spec-bundle.js:20

	SyntaxError: Use of reserved word 'import'
	at http://localhost:57484/__modules/786.js?1460747765769:3


	Error: Cannot find module '786'
	at http://localhost:57484/wallaby-webpack.js?1460747765774:1


	From console:
		hello `About` component at src/app/about/about.ts:26
```

And in the wallaby console...
```
Runtime error: Error: Cannot find module '786'
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:57484/__modules/786.js?1460747765769:3
Runtime error: Error: Cannot find module '786'
at http://localhost:57484/wallaby-webpack.js?1460747765774:1
Finished executing 1 affected test(s)
```

If you look at the URL it's reporting, the TypeScript isn't being compiled to ES5:
```javascript
window.__moduleBundler.cache[786] = [function(__webpack_require__, module, exports) {// app/about/about.spec.ts

import {
  it,
  inject,
  describe,
  beforeEachProviders
} from 'angular2/testing';

// Load the implementations that should be tested
import {About} from './about';

describe('About', () => {
  beforeEachProviders(() => [
    About
  ]);

  it('should log ngOnInit', inject([ About ], (about) => {

    spyOn(console, 'log');
    expect(console.log).not.toHaveBeenCalled();

    about.ngOnInit();
    expect(console.log).toHaveBeenCalled();
  }));

});

}, window.__moduleBundler.deps];
```

Although a TypeScript (.ts) file, there are no TypeScript features being used.  If I simply add any TypeScript element (notice 'any' type):

```javascript
// app/about/about.spec.ts
import {
  it,
  inject,
  describe,
  beforeEachProviders
} from 'angular2/testing';

// Load the implementations that should be tested
import {About} from './about';

describe('About', () => {
  beforeEachProviders(() => [
    About
  ]);

  it('should log ngOnInit', inject([ About ], (about: any) => {

    spyOn(console, 'log');
    expect(console.log).not.toHaveBeenCalled();

    about.ngOnInit();
    expect(console.log).toHaveBeenCalled();
  }));

});
```

Everything works fine!  Weird.  I don't have this issue on any of my non-webpack projects.

btw after I add the typescript-specific syntax back in (e.g. type or decorator) I need to restart wallaby to get everything back to normal.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var helpers = require('./helpers');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'config/spec-bundle.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.json$/, loader: 'json-loader', exclude: [helpers.root('src/index.html')]},
      // support for auth-lock
      {
        test: /node_modules[\\\/]auth0-lock[\\\/].*\.js$/,
        loaders: [
          'transform-loader/cacheable?brfs',
          'transform-loader/cacheable?packageify'
        ]
      }, {
        test: /node_modules[\\\/]auth0-lock[\\\/].*\.ejs$/,
        loader: 'transform-loader/cacheable?ejsify'
      }
    ]
  }
});

module.exports = function () {

  //noinspection JSUnusedGlobalSymbols
  return {
    files: [
      {pattern: 'config/spec-bundle.js', load: false},
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'test/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    env: {
      runner: require('phantomjs-prebuilt').path,
      params: { runner: '--web-security=false' }
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      //noinspection JSUnresolvedVariable,JSUnresolvedFunction
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

WebStorm WS-145.969.8
Build #WS-145.969, built on April 14, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version

OSX 10.11.4

**Comment by ArtemGovorov** [comment]
Interesting issue, thanks for providing the details!

I'm trying to reproduce it on this project: https://github.com/wallabyjs/angular2-webpack-starter (given how close its config is similar yours, I'm assuming you've used it as a boilerplate for your project), but everything seems to work for me.

Perhaps there's something different between the sample project and yours that causes the issue. Could you please try cloning [the project](https://github.com/wallabyjs/angular2-webpack-starter), running `npm i` and starting wallaby.js? The [`about.spec.ts`](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/src/app/about/about.spec.ts) is almost identical to yours (and doesn't contain any TypeScript syntax that is not ES6 syntax). If it works for you, could you please have a look into what's different in your project (maybe newer/different versions some versions of some packages in `package.json`, etc.)?

**Comment by carlansley** [comment]
Just cloned angular2-webpack-starter, npm install, it fails in the same way:

```
wallaby.js started
core v1.0.216
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/788.js?1460993772406:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/789.js?1460993772407:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/790.js?1460993772408:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/791.js?1460993772409:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/788.js?1460993772406:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/789.js?1460993772407:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/790.js?1460993772408:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/791.js?1460993772409:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/788.js?1460993772406:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/789.js?1460993772407:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/790.js?1460993772408:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/791.js?1460993772409:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/788.js?1460993772406:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/789.js?1460993772407:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/790.js?1460993772408:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/791.js?1460993772409:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/788.js?1460993772406:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/789.js?1460993772407:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/790.js?1460993772408:1
Runtime error: SyntaxError: Use of reserved word 'import'
at http://localhost:51760/__modules/791.js?1460993772409:1
Runtime error: Error: Cannot find module '788'
Runtime error: Error: Cannot find module '788'
Runtime error: Error: Cannot find module '788'
Runtime error: Error: Cannot find module '788'
Runtime error: Error: Cannot find module '788'
console.log: `About` component loaded asynchronously
```

I'm running the latest WebStorm 2016.1 EAP, maybe that's it?   It's a new WebStorm project, same package.json, not sure what else it could be.

**Comment by ArtemGovorov** [comment]
I'll test in the latest WebStorm EAP. Could you please also tell your node.js version?

**Comment by carlansley** [comment]
5.10

**Comment by ArtemGovorov** [comment]
@carlansley Ok, I found out what the issue is, it is webpack 1.13.0, works fine with webpack 1.12.15. So as a workaround you may use the 1.12.15 version for now, I'll be looking into what exactly has changed and how to support it in `wallaby-webpack`.

**Comment by ArtemGovorov** [comment]
Here what was happening: 

- [This hack](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/config/spec-bundle.js#L45) in the `spec-bundle` file is only required for karma, wallaby doesn't really need it. But it used to work in wallaby because `require.context` was requiring files that webpack couldn't parse anyway, so it would just emit empty modules.

- In v1.13.0 webpack introduced support for [ES6 modules parsing](https://github.com/webpack/webpack/commit/f6e23e3b78e3bf79e606b7a4b40d320982694696), so now webpack understands ES6, and if the file is pure ES6, it just emits a module with it, as is. When you add some TypeScript specific stuff, webpack stops understanding it and still generates an empty module.

The solution is to only execute the hack for karma and not for wallaby. Because webpack processes the  `spec-bundle` file and generates modules during the compilation, it's not possible to just add a `if (window.__karma__)` condition.

What I have done in [the sample](https://github.com/wallabyjs/angular2-webpack-starter) to make it work:
- moved the hack to a [new `karma-require.js` file](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/config/karma-require.js),
- required the file from the [`spec-bundle.js`](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/config/spec-bundle.js#L37),
- made the file to be NOT processed by [webpack for wallaby](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/wallaby.js#L13) (you'll also need to `npm i null-loader --save-dev` and add the [file to the `files` list](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/wallaby.js#L23)).

Another solution would be to have 2 separate `spec-bundle` files for wallaby and karma, where they would `require` the common part, and then karma file would also contain the hack. This would require less changes to wallaby config, but 3 file in total as opposed to 2 in the solution suggested above.

Let me know if it fixes the issue for you.

**Comment by carlansley** [comment]
Yes it does, thanks for the quick resolution!
