### ISSUE TITLE
Error: "n is not a function" with Angular 13.1.0 Project (but works with 13.0.0)

### ISSUE THREAD

**Issue by strabu** [wallabyjs/public#2877]
### Issue description or question
Wallaby does not work in VSCode with a new Angular 13.1.0 project.

Error: Failed to load configuration file: Automatic Angular CLI configuration error: n is not a function

npm install -g @angular/cli
ng --version
Angular CLI: 13.1.1
Node: 14.18.1 (-> I've also tried with 16.13.1 with same result)
Package Manager: npm 6.14.15
OS: win32 x64
Angular: 13.1.0

ng new foo
ng test
TOTAL: 3 SUCCESS

in VSCode:
>Wallaby.js Select Configuration
Automatic Configuration <project directory>
-> results in Error-Output below

It works fine when I'm changing all Angular-Packages in package.json back to Angular 13.0.0
but I'd like to use Angular 13.1.0.
(We've tried this also with different People's PCs and different projects.)

Thanks for your support and big compliments for your outstanding product.

greetings,
Alex

### Wallaby diagnostics report

‍​[Info]​ Started Wallaby.js Core v1.0.1192
​[Info]​ - Generating browser application bundles (phase: setup)...
​​[Error] Failed to load configuration file: Automatic Angular CLI configuration error: n is not a function
​​
​​[Error] 
​​
​​[Error] We've also tried to automatically configure Wallaby.js for other frameworks
​​
​​[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'.​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html​​

**Comment by smcenlly** [comment]
Thanks for reporting the problem. Looks like something in the latest version of Angular has broken Wallaby. We are working on this as a priority.

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by strabu** [comment]
Thanks a lot for your quick support.
It works again for me with: Wallaby.js Core v1.0.1193
