### ISSUE TITLE
wallaby.js + mocha@2.5.3 raises error 'this.parent.isPending is not a function'

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#648]
### Issue description or question
Starting to display error as below with mocha@2.5.3, while it was working with @2.4.5 with same configurations. Not sure if it's needed to update configurations. 

>​0 failing tests, 0 passing
​
​TypeError: this.parent.isPending is not a function
​ d:\github\rxjs\spec\observables\dom\ajax-spec.ts:13:2
​ d:\github\rxjs\spec\helpers\testScheduler-ui.ts:54
​ d:\github\rxjs\spec\observables\dom\ajax-spec.ts:9:0

### Wallaby.js configuration file

codebase in https://github.com/ReactiveX/rxjs with configurations below

```javascript
module.exports = wallaby => ({
  files: [
    'src/**/*.ts',
    {pattern: 'spec/helpers/*.ts', instrument: false}
  ],

  tests: ['spec/**/*-spec.ts'],

  compilers: {
    '**/*.ts': wallaby.compilers.typeScript({
      module: 1,  // commonjs
      target: 1,  // ES5
      preserveConstEnums: true,
    })
  },

  env: {
    type: 'node'
  },

  workers: {initial: 1, regular: 1},

  bootstrap: function (w) {
    // Remapping all require calls to `dist/cjs` right to `src`
    const Module = require('module').Module;
    if (!Module._originalRequire) {
      const modulePrototype = Module.prototype;
      Module._originalRequire = modulePrototype.require;
      modulePrototype.require = function (filePath) {
        return Module._originalRequire.call(this, filePath.replace('dist/cjs', 'src'));
      };
    }

    // Global test helpers
    global.mocha = require('mocha');
    global.Suite = global.mocha.Suite;
    global.Test = global.mocha.Test;
    require('./spec/helpers/test-helper');
    require('./spec/helpers/ajax-helper');

    //delete global context due to avoid issue by reusing process
    //https://github.com/wallabyjs/public/issues/536
    if (global.asDiagram) {
      delete global.asDiagram;
    }

    const mocha = wallaby.testFramework;
    const path = require('path');
    mocha.ui(path.resolve(w.projectCacheDir, 'spec/helpers/testScheduler-ui'));
  }
});
```

### Code editor or IDE name and version

Visual Studio Code 1.2.0

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Sent the PR: https://github.com/ReactiveX/rxjs/pull/1767. It makes wallaby to use `mocha` module from local node modules as opposed to using its embedded one.

**Comment by kwonoj** [comment]
Huge appreciate for fast help! :+1:
