### ISSUE TITLE
Wallaby doesn't start after update to Angular 14: Automatic Angular CLI configuration error

### ISSUE THREAD

**Issue by valentinstn** [wallabyjs/public#3068]
### Issue description or question

We recently migrated from Angular 11 to 14. Since then, Wallaby doesn't start anymore on my system. It immediately shows the following error message:

```
Automatic Angular CLI configuration error: Cannot find module '@angular/cli/commands/test-impl'
Require stack:
- .\wallaby.js

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Jest configuration error: Module jest-cli is not found in '.'.
```

Some details

- Wallaby: `1.0.252`.
- Node: `16.13.0`.
- I'm using the automatic configuration.
- It happens in both PyCharm and VS Code.
- It worked before the update to Angular 14 -> doesn't work in either 14.0 or 14.2 (tried both).
- I already tried to clear `node_modules` and `.angular` folder, but doesn't help.
- It seems to work flawlessly on colleague systems.

### Wallaby diagnostics report

I'm sorry, but I cannot add a diagnostics report, because the button is grayed out.

**Comment by smcenlly** [comment]
Wallaby has two version components:

1. Extension version (`v1.0.252`), and
2. Wallaby core version (the Wallaby runtime).

The Wallaby extension is evergreen but if your license has expired, Wallaby will use the runtime that is last supported by your license.

When Angular 14 was released, we needed to make some changes to Wallaby to support the latest version (https://github.com/wallabyjs/public/issues/2951).

We have just tested a new Angular 14.2 project and Wallaby is working for us, so we expect that you're experiencing an issue because your license has expired. If this is the case, you may [request a free trial license](https://wallabyjs.com/download/#try-it-free) to confirm that Wallaby is working with the latest version of Wallaby core (`v1.0.1328`).

---

If your license has not expired, the next likely cause of your problem is a bad Angular upgrade. We have seen this a number of times in the past and it is caused because of errors in Angular upgrade scripts. In this case, you may create a new Angular project using the latest CLI (e.g. 14.2) and then find and fix the differences between your upgraded project and the new project.

**Comment by valentinstn** [comment]
@smcenlly thank you! It works again after updating Wallaby Core.
