### ISSUE TITLE
`jasmine node module is not found` despite being installed

### ISSUE THREAD

**Issue by stevegreatrex** [wallabyjs/public#704]
### Issue description or question
I am trying to run wallaby using jasmine & node in typescript but wallabj insists that the jasmine node module is not found (despite being installed both locally as suggested by the error message and globally).

![example](https://cloud.githubusercontent.com/assets/854480/17076061/01eb919e-50a0-11e6-97c4-61587c03814e.png)

### Wallaby.js configuration file

```javascript
module.exports = function(w) {
    return {
        files: [
            'src/**/*.ts'
        ],
        tests: [
            'spec/**/*.[sS]pec.ts'
        ],
        compilers: {
            '**/*.ts': w.compilers.typeScript({ module: 'commonjs' })
        },
        env: {
            type: 'node'
        },
        testFramework: 'jasmine'
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.3.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Wallaby doesn't use the globally installed jasmine, and needs a locally installed one. It looks like wallaby can't find some of its parts for some reason. 

Does running 
```
./node_modules/.bin/jasmine
```
in the project folder work?
I have also just updated the core to include more details to the reported error, try [forcing the core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), running wallaby and checking the extended error message.

**Comment by stevegreatrex** [comment]
Directly calling `./node_modules/.bin/jasmine` works from the project folder.

I've updated the core and run again with `debug: true` but the error message is pretty much the same:

![image](https://cloud.githubusercontent.com/assets/854480/17076597/129d8e30-50ae-11e6-82ae-1c8a42e13b8c.png)

**Comment by ArtemGovorov** [comment]
> the error message is pretty much the same

There's some new information in the error message that wasn't there in the previous version:
```
Cannot find module 'jasmine'
```
This is very unusual because all wallaby does is this:
```javascript
var Jasmine = require('jasmine');
```
and it causes the error.
Looks like something is wrong/interfering with node modules resolution. Could you please try adding some logging like this to your config:
```javascript
module.exports = function(w) {

    try {
        require('express');
        console.log('express is found...');
    }
    catch(e){
        console.log('expres is not found...');
    }
    try {
        require('jasmine');
        console.log('jasmine is found...');
    }
    catch(e){
        console.log('jasmine is not found...');
        console.log('process.cwd()', process.cwd());
    }

    return {
    ...
```
and paste the Wallaby Console output?

**Comment by stevegreatrex** [comment]
Looks like the modules are there but I still get the same error.  Any other way to debug?

```
[Info] express is found...
[Info] jasmine is found...
[Info] Started Wallaby.js Core v1.0.267
[Info] Sat, 23 Jul 2016 08:01:57 GMT wallaby:fs File added: src/App.ts
[Info] Sat, 23 Jul 2016 08:01:57 GMT wallaby:fs File added: src/_all.d.ts
[Info] Sat, 23 Jul 2016 08:01:57 GMT wallaby:fs File added: src/routes/Reviews.ts
[Info] Sat, 23 Jul 2016 08:01:57 GMT wallaby:fs File added: spec/routes/Reviews.Spec.ts
[Info] Sat, 23 Jul 2016 08:01:58 GMT wallaby:project File cache: C:\Users\Steve\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.20\projects\00d337dc4c1ffe02
[Info] Sat, 23 Jul 2016 08:01:59 GMT wallaby:uiService Listening port 51235
[Info] Sat, 23 Jul 2016 08:01:59 GMT wallaby:project package.json file change detected, invalidating local cache
[Info] Sat, 23 Jul 2016 08:01:59 GMT wallaby:workers Parallelism for initial run: 2, for regular run: 2
[Info] Sat, 23 Jul 2016 08:01:59 GMT wallaby:workers Starting run worker instance #0
[Info] Sat, 23 Jul 2016 08:01:59 GMT wallaby:workers Starting run worker instance #1
[Info] Sat, 23 Jul 2016 08:01:59 GMT wallaby:workers Web server is listening at 50739
[Info] Sat, 23 Jul 2016 08:01:59 GMT wallaby:project File cache requires some updates, waiting required files from IDE
[Info] Sat, 23 Jul 2016 08:01:59 GMT wallaby:project File src/App.ts changes are patches only: false
[Info] Sat, 23 Jul 2016 08:01:59 GMT wallaby:project File src/_all.d.ts changes are patches only: false
[Info] Sat, 23 Jul 2016 08:01:59 GMT wallaby:project File src/routes/Reviews.ts changes are patches only: false
[Info] Sat, 23 Jul 2016 08:02:00 GMT wallaby:project File spec/routes/Reviews.Spec.ts changes are patches only: false
[Info] Sat, 23 Jul 2016 08:02:00 GMT wallaby:project Preparing to process src/App.ts
[Info] Sat, 23 Jul 2016 08:02:00 GMT wallaby:project Starting processor pool (if not yet started)
[Info] Sat, 23 Jul 2016 08:02:00 GMT wallaby:project Preparing to process src/_all.d.ts
[Info] Sat, 23 Jul 2016 08:02:00 GMT wallaby:project Starting processor pool (if not yet started)
[Info] Sat, 23 Jul 2016 08:02:00 GMT wallaby:project Preparing to process src/routes/Reviews.ts
[Info] Sat, 23 Jul 2016 08:02:00 GMT wallaby:project Starting processor pool (if not yet started)
[Info] Sat, 23 Jul 2016 08:02:00 GMT wallaby:project Preparing to process spec/routes/Reviews.Spec.ts
[Info] Sat, 23 Jul 2016 08:02:00 GMT wallaby:project Starting processor pool (if not yet started)
[Info] Sat, 23 Jul 2016 08:02:01 GMT wallaby:workers Started run worker instance (delayed) #1
[Info] Sat, 23 Jul 2016 08:02:02 GMT wallaby:workers Started run worker instance (delayed) #0
[Info] express is found...
[Info] express is found...
[Info] express is found...
[Info] express is found...
[Info] jasmine is found...
[Info] Sat, 23 Jul 2016 08:02:02 GMT wallaby:project File src/App.ts is not instrumented by core
[Info] Sat, 23 Jul 2016 08:02:02 GMT wallaby:processor No compilers found for src/App.ts
[Info] Sat, 23 Jul 2016 08:02:02 GMT wallaby:project No preprocessors configured for src/App.ts
[Info] Sat, 23 Jul 2016 08:02:02 GMT wallaby:project Writing to disk and caching processed file src/App.ts
[Info] Sat, 23 Jul 2016 08:02:02 GMT wallaby:project File src/App.ts changes saved, store ts: 1469248525000, change ts: 1469260919825
[Info] jasmine is found...
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project File src/_all.d.ts is not instrumented by core
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:processor No compilers found for src/_all.d.ts
[Info] jasmine is found...
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:processor No compilers found for src/routes/Reviews.ts
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project No preprocessors configured for src/_all.d.ts
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Writing to disk and caching processed file src/_all.d.ts
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project File src/routes/Reviews.ts is not instrumented by core
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project No preprocessors configured for src/routes/Reviews.ts
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Writing to disk and caching processed file src/routes/Reviews.ts
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project File src/_all.d.ts changes saved, store ts: 1469251856000, change ts: 1469260919901
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project File src/routes/Reviews.ts changes saved, store ts: 1469242976000, change ts: 1469260919981
[Info] jasmine is found...
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:processor No compilers found for spec/routes/Reviews.Spec.ts
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project File spec/routes/Reviews.Spec.ts is not instrumented by core
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project No preprocessors configured for spec/routes/Reviews.Spec.ts
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Writing to disk and caching processed file spec/routes/Reviews.Spec.ts
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project File spec/routes/Reviews.Spec.ts changes saved, store ts: 1469260902000, change ts: 1469260920054
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Stopping process pool
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Running postprocessor
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:postprocessor New TypeScript language service is required
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Preparing to process src/App.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Preparing to process src/routes/Reviews.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Preparing to process spec/routes/Reviews.Spec.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Processing compiled src/App.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Instrumenting src/App.js, via process pool: false
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Processing compiled src/routes/Reviews.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Instrumenting src/routes/Reviews.js, via process pool: false
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Processing compiled spec/routes/Reviews.Spec.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Instrumenting spec/routes/Reviews.Spec.js, via process pool: false
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project No preprocessors configured for src/App.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project No preprocessors configured for src/routes/Reviews.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project No preprocessors configured for spec/routes/Reviews.Spec.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Writing to disk and caching processed file src/App.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Writing to disk and caching processed file src/routes/Reviews.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Writing to disk and caching processed file spec/routes/Reviews.Spec.js
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Postprocessor execution finished
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Test run started; run priority: 3
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Running all tests
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:workers Starting test run, priority: 3
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #rj3wp]
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #rj3wp]
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #rj3wp]
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:workers Running tests in sandbox [worker #0, session #rj3wp]
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:workers Sandbox (active) [rj3wp] error: jasmine node module is not found or the version is not supported, missing `npm install jasmine --save-dev`?
[Error] Runtime error: jasmine node module is not found or the version is not supported, missing `npm install jasmine --save-dev`?
[Error] Cannot find module 'jasmine'
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:workers Failed to map the stack to user code, entry message: jasmine node module is not found or the version is not supported, missing `npm install jasmine --save-dev`?, stack: jasmine node module is not found or the version is not supported, missing `npm install jasmine --save-dev`?
[Info] Cannot find module 'jasmine'
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:workers Sandbox [rj3wp] is responsive, closing it
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Test run finished
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Processed console.log entries
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Processed loading sequences
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Processed executed tests
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Processed code coverage
[Info] Sat, 23 Jul 2016 08:02:03 GMT wallaby:project Test run result processed and sent to IDE
```

**Comment by ArtemGovorov** [comment]
Please try this (you may also set `debug: false` for now):
```javascript
module.exports = function(w) {
    console.log(require('module').Module._nodeModulePaths(''));
    return {
    ...
```

**Comment by ArtemGovorov** [comment]
What is your node.js version BTW?

**Comment by stevegreatrex** [comment]
Realised my node version is pretty old (`0.10.29`) so updating that now...

```
[Info] [ 'c:\\Users\\Steve\\Desktop\\reviewme\\node_modules',
[Info]   'c:\\Users\\Steve\\Desktop\\node_modules',
[Info]   'c:\\Users\\Steve\\node_modules',
[Info]   'c:\\Users\\node_modules',
[Info]   'c:\\node_modules',
[Info]   'c:\\Users\\Steve\\Desktop\\reviewme\\node_modules' ]
[Info] Started Wallaby.js Core v1.0.267
[Info] [ 'c:\\Users\\Steve\\Desktop\\reviewme\\node_modules',
[Info]   'c:\\Users\\Steve\\Desktop\\node_modules',
[Info]   'c:\\Users\\Steve\\node_modules',
[Info]   'c:\\Users\\node_modules',
[Info]   'c:\\node_modules' ]
[Info] [ 'c:\\Users\\Steve\\Desktop\\reviewme\\node_modules',
[Info]   'c:\\Users\\Steve\\Desktop\\node_modules',
[Info]   'c:\\Users\\Steve\\node_modules',
[Info]   'c:\\Users\\node_modules',
[Info]   'c:\\node_modules' ]
[Info] [ 'c:\\Users\\Steve\\Desktop\\reviewme\\node_modules',
[Info]   'c:\\Users\\Steve\\Desktop\\node_modules',
[Info]   'c:\\Users\\Steve\\node_modules',
[Info]   'c:\\Users\\node_modules',
[Info]   'c:\\node_modules' ]
[Info] [ 'c:\\Users\\Steve\\Desktop\\reviewme\\node_modules',
[Info]   'c:\\Users\\Steve\\Desktop\\node_modules',
[Info]   'c:\\Users\\Steve\\node_modules',
[Info]   'c:\\Users\\node_modules',
[Info]   'c:\\node_modules' ]
[Error] Runtime error: jasmine node module is not found or the version is not supported, missing `npm install jasmine --save-dev`?
[Error] Cannot find module 'jasmine'
```

**Comment by ArtemGovorov** [comment]
No worries at all, thanks for the update! My fault, I should have asked about the node version initially. And for sure wallaby should do a better job checking supported node versions and reporting it.

We have started developing wallaby with 0.12 or io.js (don't exactly remember), and shipping the node version for IntelliJ platform and Visual Studio. Later we started to ship a newer version of node, but for VS Code, Atom we don't do it and just use whatever the user's version is. 

I'll find out what's the least supported version and will add a warning message if it's not something that we support. Thanks for your help!

**Comment by jmwnoble** [comment]
Hi Artem, I just ran into this issue with v1.0.359, node v6.9.4 on latest VSCode on windows 10. Jasmine 2.5.3 is installed in the project (and jasmine-node for good measure).  Ran same checks you noted above with exactly the same results.  Any thoughts?

**Comment by jmwnoble** [comment]
After further investigation, I am going to venture that this is caused by #68 since I had a wallaby.ts file that was compiling to a wallaby.js file one folder down, hence couldn't reference the parent directory.  Whoops.
